//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.296
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveElementsIntTest.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯你的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建你的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FiveElementsIntTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap arrow {
            get {
                object obj = ResourceManager.GetObject("arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArrowTexLeft {
            get {
                object obj = ResourceManager.GetObject("ArrowTexLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArrowTexRight {
            get {
                object obj = ResourceManager.GetObject("ArrowTexRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArrowTexUp {
            get {
                object obj = ResourceManager.GetObject("ArrowTexUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AxeTex {
            get {
                object obj = ResourceManager.GetObject("AxeTex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BAR {
            get {
                object obj = ResourceManager.GetObject("BAR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BLANK {
            get {
                object obj = ResourceManager.GetObject("BLANK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BLANK_TEX {
            get {
                object obj = ResourceManager.GetObject("BLANK_TEX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CIRCLE {
            get {
                object obj = ResourceManager.GetObject("CIRCLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CROSS {
            get {
                object obj = ResourceManager.GetObject("CROSS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CSDarkblueCircle {
            get {
                object obj = ResourceManager.GetObject("CSDarkblueCircle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CSLightblueCircle {
            get {
                object obj = ResourceManager.GetObject("CSLightblueCircle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CSTriangle {
            get {
                object obj = ResourceManager.GetObject("CSTriangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CubeArrowBackAnti {
            get {
                object obj = ResourceManager.GetObject("CubeArrowBackAnti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CubeArrowBackClock {
            get {
                object obj = ResourceManager.GetObject("CubeArrowBackClock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CubeArrowDownAnti {
            get {
                object obj = ResourceManager.GetObject("CubeArrowDownAnti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CubeArrowDownClock {
            get {
                object obj = ResourceManager.GetObject("CubeArrowDownClock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CubeArrowFrontAnti {
            get {
                object obj = ResourceManager.GetObject("CubeArrowFrontAnti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CubeArrowFrontClock {
            get {
                object obj = ResourceManager.GetObject("CubeArrowFrontClock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CubeArrowLeftAnti {
            get {
                object obj = ResourceManager.GetObject("CubeArrowLeftAnti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CubeArrowLeftClock {
            get {
                object obj = ResourceManager.GetObject("CubeArrowLeftClock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CubeArrowRightAnti {
            get {
                object obj = ResourceManager.GetObject("CubeArrowRightAnti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CubeArrowRightClock {
            get {
                object obj = ResourceManager.GetObject("CubeArrowRightClock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CubeArrowUpAnti {
            get {
                object obj = ResourceManager.GetObject("CubeArrowUpAnti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CubeArrowUpClock {
            get {
                object obj = ResourceManager.GetObject("CubeArrowUpClock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DemoCtSpan {
            get {
                object obj = ResourceManager.GetObject("DemoCtSpan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DOUBLE_ARROW {
            get {
                object obj = ResourceManager.GetObject("DOUBLE_ARROW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HalfTexDwonLeft {
            get {
                object obj = ResourceManager.GetObject("HalfTexDwonLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HalfTexDwonRight {
            get {
                object obj = ResourceManager.GetObject("HalfTexDwonRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HalfTexUpLeft {
            get {
                object obj = ResourceManager.GetObject("HalfTexUpLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HalfTexUpRight {
            get {
                object obj = ResourceManager.GetObject("HalfTexUpRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ITF_EXAMPLE {
            get {
                object obj = ResourceManager.GetObject("ITF_EXAMPLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LINELEFT {
            get {
                object obj = ResourceManager.GetObject("LINELEFT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LINEMASK {
            get {
                object obj = ResourceManager.GetObject("LINEMASK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LINERIGHT {
            get {
                object obj = ResourceManager.GetObject("LINERIGHT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SlashTexULRD {
            get {
                object obj = ResourceManager.GetObject("SlashTexULRD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SlashTexURLD {
            get {
                object obj = ResourceManager.GetObject("SlashTexURLD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SLECTED {
            get {
                object obj = ResourceManager.GetObject("SLECTED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        internal static string string1 {
            get {
                return ResourceManager.GetString("string1", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SymSrhInstruction1 {
            get {
                object obj = ResourceManager.GetObject("SymSrhInstruction1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SymSrhInstruction2 {
            get {
                object obj = ResourceManager.GetObject("SymSrhInstruction2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap X {
            get {
                object obj = ResourceManager.GetObject("X", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
